# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/User/Downloads/project/test_bram/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Downloads/project/test_bram/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths c:/Users/User/Downloads/project/test_bram [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/User/Downloads/project/test_bram/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_blk_mem_gen_i0_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_blk_mem_gen_i1_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i0_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i1_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i10_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i11_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i12_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i13_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i14_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i15_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i16_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i17_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i18_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i19_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i2_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i20_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i21_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i22_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i23_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i24_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i25_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i26_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i27_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i28_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i29_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i3_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i30_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i31_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i32_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i33_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i34_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i35_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i36_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i37_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i38_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i39_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i4_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i40_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i41_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i42_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i43_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i44_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i45_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i46_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i47_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i48_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i49_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i5_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i50_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i51_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i52_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i53_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i54_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i55_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i56_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i57_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i58_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i59_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i6_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i60_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i61_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i7_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i8_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_c_shift_ram_v12_0_i9_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i0_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i1_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i2_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i3_vivado.coe
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i4_vivado.coe
read_verilog -library xil_defaultlib C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/constrs/awgn_inv_mapping.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_blk_mem_gen_i0/awgn_inv_mapping_blk_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_blk_mem_gen_i1/awgn_inv_mapping_blk_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i0/awgn_inv_mapping_dist_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i1/awgn_inv_mapping_dist_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i2/awgn_inv_mapping_dist_mem_gen_i2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i3/awgn_inv_mapping_dist_mem_gen_i3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_awgn_inv_mapping_0_0/awgn_inv_mapping_dist_mem_gen_i4/awgn_inv_mapping_dist_mem_gen_i4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/User/Downloads/project/test_bram/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
