# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_bd_awgn_inv_mapping_1_0.xci
# IP: The module: 'awgn_inv_mapping_bd_awgn_inv_mapping_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i0/awgn_inv_mapping_blk_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_blk_mem_gen_i0 || ORIG_REF_NAME==awgn_inv_mapping_blk_mem_gen_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i1/awgn_inv_mapping_blk_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_blk_mem_gen_i1 || ORIG_REF_NAME==awgn_inv_mapping_blk_mem_gen_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_addsub_v12_0_i0/awgn_inv_mapping_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_addsub_v12_0_i1/awgn_inv_mapping_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i0/awgn_inv_mapping_c_shift_ram_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i1/awgn_inv_mapping_c_shift_ram_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i10/awgn_inv_mapping_c_shift_ram_v12_0_i10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i10 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i10} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i11/awgn_inv_mapping_c_shift_ram_v12_0_i11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i11 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i11} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i12/awgn_inv_mapping_c_shift_ram_v12_0_i12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i12 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i12} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i13/awgn_inv_mapping_c_shift_ram_v12_0_i13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i13 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i13} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i14/awgn_inv_mapping_c_shift_ram_v12_0_i14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i14 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i14} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i15/awgn_inv_mapping_c_shift_ram_v12_0_i15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i15 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i15} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i16/awgn_inv_mapping_c_shift_ram_v12_0_i16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i16 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i16} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i17/awgn_inv_mapping_c_shift_ram_v12_0_i17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i17 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i17} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i18/awgn_inv_mapping_c_shift_ram_v12_0_i18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i18 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i18} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i19/awgn_inv_mapping_c_shift_ram_v12_0_i19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i19 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i19} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i2/awgn_inv_mapping_c_shift_ram_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i2 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i20/awgn_inv_mapping_c_shift_ram_v12_0_i20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i20 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i20} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i21/awgn_inv_mapping_c_shift_ram_v12_0_i21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i21 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i21} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i22/awgn_inv_mapping_c_shift_ram_v12_0_i22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i22 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i22} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i23/awgn_inv_mapping_c_shift_ram_v12_0_i23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i23 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i23} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i24/awgn_inv_mapping_c_shift_ram_v12_0_i24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i24 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i24} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i25/awgn_inv_mapping_c_shift_ram_v12_0_i25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i25 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i25} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i26/awgn_inv_mapping_c_shift_ram_v12_0_i26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i26 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i26} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i27/awgn_inv_mapping_c_shift_ram_v12_0_i27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i27 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i27} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i28/awgn_inv_mapping_c_shift_ram_v12_0_i28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i28 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i28} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i29/awgn_inv_mapping_c_shift_ram_v12_0_i29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i29 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i29} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i3/awgn_inv_mapping_c_shift_ram_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i3 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i3} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i30/awgn_inv_mapping_c_shift_ram_v12_0_i30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i30 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i30} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i31/awgn_inv_mapping_c_shift_ram_v12_0_i31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i31 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i31} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i32/awgn_inv_mapping_c_shift_ram_v12_0_i32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i32 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i32} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i33/awgn_inv_mapping_c_shift_ram_v12_0_i33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i33 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i33} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i34/awgn_inv_mapping_c_shift_ram_v12_0_i34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i34 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i34} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i35/awgn_inv_mapping_c_shift_ram_v12_0_i35.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i35 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i35} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i36/awgn_inv_mapping_c_shift_ram_v12_0_i36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i36 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i36} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i37/awgn_inv_mapping_c_shift_ram_v12_0_i37.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i37 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i37} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i38/awgn_inv_mapping_c_shift_ram_v12_0_i38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i38 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i38} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i39/awgn_inv_mapping_c_shift_ram_v12_0_i39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i39 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i39} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i4/awgn_inv_mapping_c_shift_ram_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i4 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i4} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i40/awgn_inv_mapping_c_shift_ram_v12_0_i40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i40 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i40} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i41/awgn_inv_mapping_c_shift_ram_v12_0_i41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i41 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i41} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i42/awgn_inv_mapping_c_shift_ram_v12_0_i42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i42 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i42} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i43/awgn_inv_mapping_c_shift_ram_v12_0_i43.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i43 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i43} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i44/awgn_inv_mapping_c_shift_ram_v12_0_i44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i44 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i44} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i45/awgn_inv_mapping_c_shift_ram_v12_0_i45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i45 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i45} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i46/awgn_inv_mapping_c_shift_ram_v12_0_i46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i46 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i46} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i47/awgn_inv_mapping_c_shift_ram_v12_0_i47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i47 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i47} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i48/awgn_inv_mapping_c_shift_ram_v12_0_i48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i48 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i48} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i49/awgn_inv_mapping_c_shift_ram_v12_0_i49.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i49 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i49} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i5/awgn_inv_mapping_c_shift_ram_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i5 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i5} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i50/awgn_inv_mapping_c_shift_ram_v12_0_i50.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i50 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i50} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i51/awgn_inv_mapping_c_shift_ram_v12_0_i51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i51 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i51} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i52/awgn_inv_mapping_c_shift_ram_v12_0_i52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i52 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i52} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i53/awgn_inv_mapping_c_shift_ram_v12_0_i53.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i53 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i53} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i54/awgn_inv_mapping_c_shift_ram_v12_0_i54.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i54 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i54} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i55/awgn_inv_mapping_c_shift_ram_v12_0_i55.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i55 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i55} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i56/awgn_inv_mapping_c_shift_ram_v12_0_i56.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i56 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i56} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i57/awgn_inv_mapping_c_shift_ram_v12_0_i57.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i57 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i57} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i58/awgn_inv_mapping_c_shift_ram_v12_0_i58.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i58 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i58} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i59/awgn_inv_mapping_c_shift_ram_v12_0_i59.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i59 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i59} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i6/awgn_inv_mapping_c_shift_ram_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i6 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i6} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i60/awgn_inv_mapping_c_shift_ram_v12_0_i60.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i60 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i60} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i61/awgn_inv_mapping_c_shift_ram_v12_0_i61.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i61 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i61} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i7/awgn_inv_mapping_c_shift_ram_v12_0_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i7 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i7} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i8/awgn_inv_mapping_c_shift_ram_v12_0_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i8 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i8} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i9/awgn_inv_mapping_c_shift_ram_v12_0_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i9 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i9} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i0/awgn_inv_mapping_dist_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i0 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i1/awgn_inv_mapping_dist_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i1 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i2/awgn_inv_mapping_dist_mem_gen_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i2 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i3/awgn_inv_mapping_dist_mem_gen_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i3 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i3} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i4/awgn_inv_mapping_dist_mem_gen_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i4 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i4} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i0/awgn_inv_mapping_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i1/awgn_inv_mapping_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i2/awgn_inv_mapping_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i2 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i3/awgn_inv_mapping_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i3 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i3} -quiet] -quiet

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i0/awgn_inv_mapping_blk_mem_gen_i0_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i1/awgn_inv_mapping_blk_mem_gen_i1_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i0/awgn_inv_mapping_dist_mem_gen_i0_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i1/awgn_inv_mapping_dist_mem_gen_i1_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i2/awgn_inv_mapping_dist_mem_gen_i2_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i3/awgn_inv_mapping_dist_mem_gen_i3_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i4/awgn_inv_mapping_dist_mem_gen_i4_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/constrs/awgn_inv_mapping.xdc
# XDC: The top module name and the constraint reference have the same name: 'awgn_inv_mapping_bd_awgn_inv_mapping_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_bd_awgn_inv_mapping_1_0.xci
# IP: The module: 'awgn_inv_mapping_bd_awgn_inv_mapping_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i0/awgn_inv_mapping_blk_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_blk_mem_gen_i0 || ORIG_REF_NAME==awgn_inv_mapping_blk_mem_gen_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i1/awgn_inv_mapping_blk_mem_gen_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_blk_mem_gen_i1 || ORIG_REF_NAME==awgn_inv_mapping_blk_mem_gen_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_addsub_v12_0_i0/awgn_inv_mapping_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_addsub_v12_0_i1/awgn_inv_mapping_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_c_addsub_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i0/awgn_inv_mapping_c_shift_ram_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i1/awgn_inv_mapping_c_shift_ram_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i10/awgn_inv_mapping_c_shift_ram_v12_0_i10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i10 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i10} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i11/awgn_inv_mapping_c_shift_ram_v12_0_i11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i11 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i11} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i12/awgn_inv_mapping_c_shift_ram_v12_0_i12.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i12 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i12} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i13/awgn_inv_mapping_c_shift_ram_v12_0_i13.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i13 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i13} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i14/awgn_inv_mapping_c_shift_ram_v12_0_i14.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i14 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i14} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i15/awgn_inv_mapping_c_shift_ram_v12_0_i15.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i15 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i15} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i16/awgn_inv_mapping_c_shift_ram_v12_0_i16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i16 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i16} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i17/awgn_inv_mapping_c_shift_ram_v12_0_i17.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i17 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i17} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i18/awgn_inv_mapping_c_shift_ram_v12_0_i18.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i18 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i18} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i19/awgn_inv_mapping_c_shift_ram_v12_0_i19.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i19 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i19} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i2/awgn_inv_mapping_c_shift_ram_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i2 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i20/awgn_inv_mapping_c_shift_ram_v12_0_i20.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i20 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i20} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i21/awgn_inv_mapping_c_shift_ram_v12_0_i21.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i21 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i21} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i22/awgn_inv_mapping_c_shift_ram_v12_0_i22.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i22 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i22} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i23/awgn_inv_mapping_c_shift_ram_v12_0_i23.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i23 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i23} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i24/awgn_inv_mapping_c_shift_ram_v12_0_i24.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i24 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i24} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i25/awgn_inv_mapping_c_shift_ram_v12_0_i25.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i25 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i25} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i26/awgn_inv_mapping_c_shift_ram_v12_0_i26.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i26 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i26} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i27/awgn_inv_mapping_c_shift_ram_v12_0_i27.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i27 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i27} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i28/awgn_inv_mapping_c_shift_ram_v12_0_i28.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i28 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i28} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i29/awgn_inv_mapping_c_shift_ram_v12_0_i29.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i29 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i29} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i3/awgn_inv_mapping_c_shift_ram_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i3 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i3} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i30/awgn_inv_mapping_c_shift_ram_v12_0_i30.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i30 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i30} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i31/awgn_inv_mapping_c_shift_ram_v12_0_i31.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i31 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i31} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i32/awgn_inv_mapping_c_shift_ram_v12_0_i32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i32 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i32} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i33/awgn_inv_mapping_c_shift_ram_v12_0_i33.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i33 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i33} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i34/awgn_inv_mapping_c_shift_ram_v12_0_i34.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i34 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i34} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i35/awgn_inv_mapping_c_shift_ram_v12_0_i35.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i35 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i35} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i36/awgn_inv_mapping_c_shift_ram_v12_0_i36.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i36 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i36} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i37/awgn_inv_mapping_c_shift_ram_v12_0_i37.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i37 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i37} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i38/awgn_inv_mapping_c_shift_ram_v12_0_i38.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i38 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i38} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i39/awgn_inv_mapping_c_shift_ram_v12_0_i39.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i39 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i39} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i4/awgn_inv_mapping_c_shift_ram_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i4 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i4} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i40/awgn_inv_mapping_c_shift_ram_v12_0_i40.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i40 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i40} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i41/awgn_inv_mapping_c_shift_ram_v12_0_i41.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i41 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i41} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i42/awgn_inv_mapping_c_shift_ram_v12_0_i42.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i42 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i42} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i43/awgn_inv_mapping_c_shift_ram_v12_0_i43.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i43 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i43} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i44/awgn_inv_mapping_c_shift_ram_v12_0_i44.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i44 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i44} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i45/awgn_inv_mapping_c_shift_ram_v12_0_i45.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i45 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i45} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i46/awgn_inv_mapping_c_shift_ram_v12_0_i46.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i46 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i46} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i47/awgn_inv_mapping_c_shift_ram_v12_0_i47.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i47 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i47} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i48/awgn_inv_mapping_c_shift_ram_v12_0_i48.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i48 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i48} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i49/awgn_inv_mapping_c_shift_ram_v12_0_i49.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i49 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i49} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i5/awgn_inv_mapping_c_shift_ram_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i5 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i5} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i50/awgn_inv_mapping_c_shift_ram_v12_0_i50.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i50 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i50} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i51/awgn_inv_mapping_c_shift_ram_v12_0_i51.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i51 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i51} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i52/awgn_inv_mapping_c_shift_ram_v12_0_i52.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i52 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i52} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i53/awgn_inv_mapping_c_shift_ram_v12_0_i53.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i53 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i53} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i54/awgn_inv_mapping_c_shift_ram_v12_0_i54.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i54 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i54} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i55/awgn_inv_mapping_c_shift_ram_v12_0_i55.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i55 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i55} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i56/awgn_inv_mapping_c_shift_ram_v12_0_i56.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i56 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i56} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i57/awgn_inv_mapping_c_shift_ram_v12_0_i57.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i57 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i57} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i58/awgn_inv_mapping_c_shift_ram_v12_0_i58.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i58 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i58} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i59/awgn_inv_mapping_c_shift_ram_v12_0_i59.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i59 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i59} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i6/awgn_inv_mapping_c_shift_ram_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i6 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i6} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i60/awgn_inv_mapping_c_shift_ram_v12_0_i60.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i60 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i60} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i61/awgn_inv_mapping_c_shift_ram_v12_0_i61.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i61 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i61} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i7/awgn_inv_mapping_c_shift_ram_v12_0_i7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i7 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i7} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i8/awgn_inv_mapping_c_shift_ram_v12_0_i8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i8 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i8} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_c_shift_ram_v12_0_i9/awgn_inv_mapping_c_shift_ram_v12_0_i9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i9 || ORIG_REF_NAME==awgn_inv_mapping_c_shift_ram_v12_0_i9} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i0/awgn_inv_mapping_dist_mem_gen_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i0 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i1/awgn_inv_mapping_dist_mem_gen_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i1 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i2/awgn_inv_mapping_dist_mem_gen_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i2 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i3/awgn_inv_mapping_dist_mem_gen_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i3 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i3} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i4/awgn_inv_mapping_dist_mem_gen_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_dist_mem_gen_i4 || ORIG_REF_NAME==awgn_inv_mapping_dist_mem_gen_i4} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i0/awgn_inv_mapping_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i0 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i0} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i1/awgn_inv_mapping_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i1 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i1} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i2/awgn_inv_mapping_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i2 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i2} -quiet] -quiet

# IP: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_mult_gen_v12_0_i3/awgn_inv_mapping_mult_gen_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i3 || ORIG_REF_NAME==awgn_inv_mapping_mult_gen_v12_0_i3} -quiet] -quiet

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i0/awgn_inv_mapping_blk_mem_gen_i0_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_blk_mem_gen_i1/awgn_inv_mapping_blk_mem_gen_i1_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i0/awgn_inv_mapping_dist_mem_gen_i0_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i1/awgn_inv_mapping_dist_mem_gen_i1_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i2/awgn_inv_mapping_dist_mem_gen_i2_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i3/awgn_inv_mapping_dist_mem_gen_i3_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_dist_mem_gen_i4/awgn_inv_mapping_dist_mem_gen_i4_ooc.xdc

# XDC: d:/10702201/channel_coding/CHANNEL/ZB/inv_map_10_4/ip_catalog/awgn_inv_mapping.srcs/sources_1/bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/constrs/awgn_inv_mapping.xdc
# XDC: The top module name and the constraint reference have the same name: 'awgn_inv_mapping_bd_awgn_inv_mapping_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
