# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/awgn_inv_mapping_clock.xdc

# XDC: imports/sysgen/awgn_inv_mapping.xdc

# Block Designs: bd/awgn_inv_mapping_bd/awgn_inv_mapping_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_bd || ORIG_REF_NAME==awgn_inv_mapping_bd} -quiet] -quiet

# IP: bd/awgn_inv_mapping_bd/ip/awgn_inv_mapping_bd_awgn_inv_mapping_1_0/awgn_inv_mapping_bd_awgn_inv_mapping_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==awgn_inv_mapping_bd_awgn_inv_mapping_1_0 || ORIG_REF_NAME==awgn_inv_mapping_bd_awgn_inv_mapping_1_0} -quiet] -quiet

# XDC: bd/awgn_inv_mapping_bd/awgn_inv_mapping_bd_ooc.xdc
